workflows:
  ios-release:
    name: iOS Release Build

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dvapp.mothelper

    integrations:
      app_store_connect: MOT Booking Helper

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Build iOS
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
