// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1p6-MtAC7_9-DpwJKc6hzm3sFCohim1o',
    appId: '1:188755482879:web:17d5e99aff4dd34c1454ca',
    messagingSenderId: '188755482879',
    projectId: 'dvapp-87029',
    authDomain: 'dvapp-87029.firebaseapp.com',
    storageBucket: 'dvapp-87029.firebasestorage.app',
    measurementId: 'G-HVXTHB4Q3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoKLnbpGsSDPtP56Z58MKD41BsC1-i4vA',
    appId: '1:188755482879:android:4a605c37295830471454ca',
    messagingSenderId: '188755482879',
    projectId: 'dvapp-87029',
    storageBucket: 'dvapp-87029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwV7M01PUK7kO4Yf0plUGCPxTKCQhnKYg',
    appId: '1:188755482879:ios:fed736f95b3808761454ca',
    messagingSenderId: '188755482879',
    projectId: 'dvapp-87029',
    storageBucket: 'dvapp-87029.firebasestorage.app',
    iosBundleId: 'com.example.motNi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwV7M01PUK7kO4Yf0plUGCPxTKCQhnKYg',
    appId: '1:188755482879:ios:fed736f95b3808761454ca',
    messagingSenderId: '188755482879',
    projectId: 'dvapp-87029',
    storageBucket: 'dvapp-87029.firebasestorage.app',
    iosBundleId: 'com.example.motNi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1p6-MtAC7_9-DpwJKc6hzm3sFCohim1o',
    appId: '1:188755482879:web:d7e849aec6d2a0af1454ca',
    messagingSenderId: '188755482879',
    projectId: 'dvapp-87029',
    authDomain: 'dvapp-87029.firebaseapp.com',
    storageBucket: 'dvapp-87029.firebasestorage.app',
    measurementId: 'G-B7K0FYPZJQ',
  );

}